; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[platformio]
extra_configs = secret.ini
default_envs = m5stack-atoms3-lite

[base]
extra_scripts = 
    pre:inject_version.py
build_flags =
    -DPREFS_NAME='${secret.prefs_name}'
    -DUSE_AES=${secret.use_aes}
lib_deps = 

[ota]
platform = espressif32
framework = arduino
upload_protocol = espota
upload_flags = 
    --auth="${secret.ota_password}"
    --host_port=22564 

[s3core]
platform = espressif32
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
extra_scripts = 
    ${base.extra_scripts}
build_flags =
    ${base.build_flags}
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DSERIAL_SPEED=${s3core.monitor_speed}
    ; -DCORE_DEBUG_LEVEL=1
    ; -DLOG_SERIAL=Serial
; monitor_filters = esp32_exception_decoder
; build_type = debug
lib_deps = 
    ${base.lib_deps}
    TaskScheduler=https://github.com/arkhipenko/TaskScheduler
test_ignore = test_native

[m5stack]
extends = s3core
build_flags =
    ${s3core.build_flags}
    -DIS_M5=1
lib_deps =
    ${s3core.lib_deps}
    M5Unified=https://github.com/m5stack/M5Unified

[env:m5stack-atoms3-lite]
extends = m5stack
board = m5stack-atoms3
build_flags =
    ${m5stack.build_flags}
    -DBUILD_ID='"m5stack-atoms3-lite"'
    -DHAVE_RTC=0
    -DSER=Serial
    -DM_S_DUMMY=1
    ; -DLOG_UDP=1
    ; -DM_S_DUMMY=1
; monitor_filters = esp32_exception_decoder
; build_type = debug

[env:native]
platform = native
test_ignore = test_embedded
extra_scripts = 
    ${base.extra_scripts}
test_build_src = true
build_flags =
    ${base.build_flags}
    -g
    -fsanitize=address
    -DBUILD_ID='"native"'
    -DHAVE_RTC=0
    -DM_S_DUMMY=1
    -DCHIP_ID=21
lib_deps =
    ${base.lib_deps}
lib_compat_mode = off
